### ISSUE TITLE
Lỗi font chữ khu vực admin

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1157]
![untitled](https://cloud.githubusercontent.com/assets/6817130/8681840/0ef63ca0-2a94-11e5-91ad-e4046e27fc91.jpg)
Lỗi chỉ xảy ra khi truy cập "Nhật ký hệ thống"
không phải lúc nào cũng gây ra lỗi này. hiện tượng lỗi là chập chờn lúc bị lúc không nhưng bị là nhiều hơn. Nukeviet 4.0.21 last commit https://github.com/nukeviet/nukeviet/commit/309075b2e596730d03df930d8e1d7d61c5e28d14

**Comment by hoaquynhtim99** [comment]
Cái này em cũng gặp một vài lần nhưng chưa tìm ra nguyên nhân, kiểm tra console không có lỗi, đoán là do trình duyệt tải font roboto chưa kịp so với tốc độ load trang dẫn đến hiện tượng trên, test trên firefox và IE không thấy, chỉ thấy xuất hiên trên chrome nên tạm thời có thể xem là bug của trình duyệt.

**Comment by vuthao** [comment]
@hoaquynhtim99 kiểm tra xem có bản cập nhật font đó không.

**Comment by hoaquynhtim99** [comment]
@vuthao Cái này đúng là có thay đổi, hiện nay riêng Chrome sử dụng kiểu gọi font khác còn các trình duyệt khác vẫn giữ cách như cũ. Khả năng nghỉ chơi với cái này, nếu sử dụng php để nhận diện trình duyệt thì quá phức tạp, nếu gọi font từ google luôn thì ok nhưng laij không chạy được nếu không có internet

**Comment by thehung** [comment]
Sao không nạp trực tiếp font từ website mà phải qua google?

Dũng thử kiểm tra xem sử dụng roboto font của google có bị lỗi này không?

**Comment by hoaquynhtim99** [comment]
@thehung Robot của google hiện tại nó đã cập nhật khác, trình gọi của nó phát hiện được trình duyệt, nếu là Chrome thì nó sẽ trả về đoạn mã khác mà nếu là các trình duyệt khác thì nó trả về đoạn mã cổ điển như NukeViet vẫn đang sử dụng.

**Comment by thehung** [comment]
Anh không hiểu: vậy robot thì liên quan gì đến việc hiển thị bị lỗi?

**Comment by hoaquynhtim99** [comment]
Em viết nhầm, đại loại là thế này:
- Nếu truy cập bằng Chrome thì google nó đưa mã CSS về như sau:
```css
/* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/ek4gzZ-GeXAPcSbHtCeQI_esZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
}
/* cyrillic */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/mErvLBYg_cXG3rLvUsKT_fesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/-2n2p-_Y08sg57CNWQfKNvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/u0TOpm082MNkS5K0Q4rhqvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/NdF9MtnOpLzo-noMoG0miPesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0102-0103, U+1EA0-1EF1, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/Fcx7Wwv8OzT71A3E1XOAjvesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```
- Nếu truy cập bằng các trình duyệt khác thì
```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(http://fonts.gstatic.com/s/roboto/v15/HV_H5nosKj8mZupFxrHqHA.woff) format('woff');
}
```

Kiểu mã thứ 2 hiện mình đang sử dụng nhưng gặp lỗi trên Chrome như hiện tại, còn kiểu mã thứ 1 thì không chạy trên các trình duyệt khác
