### ISSUE TITLE
Lỗi font chữ khu vực admin

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1420]
Hệ điều hành windows 10
Trình duyệt:  chrome  Phiên bản 44.0.2403.157
![loi font](https://cloud.githubusercontent.com/assets/6817130/9491008/22b217fc-4c16-11e5-85dc-fbe450053b85.png)

**Comment by anhtunguyen** [comment]
Theo anh bỏ quách cái webfont trong admin đi Thảo, dùng font mặc định của bootstrap cho nó nhẹ nhàng. Hiện tại cái font roboto của mình chỉ hỗ trợ IE và FF, còn Chrome nó lại dùng font riêng.

**Comment by vuthao** [comment]
Để em kiểm tra xem có fix được không, nếu không fix ngay được tối mai sẽ tạm thời tắt nó đi.

**Comment by hoaquynhtim99** [comment]
Có hướng dẫn thêm đoạn CSS

```css
body {
    -webkit-animation-delay: 0.1s;
    -webkit-animation-name: fontfix;
    -webkit-animation-duration: 0.1s;
    -webkit-animation-iteration-count: 1;
    -webkit-animation-timing-function: linear;
}

@-webkit-keyframes fontfix {
    from { opacity: 1; }
    to   { opacity: 1; }
}
```

Máy em test đủ kiểu không ra lỗi nữa nên chẳng biết thế nào.
