### ISSUE TITLE
Css khó hiểu

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#448]
Giao diện admin module news 

``` css
.fa {
cursor: help;
}
```

Tại sao các icon lại phải để trỏ chuột là dấu chấm hỏi trong khi không phải icon nào cũng nhằm mục đích chú thích.
